# -*- coding: utf-8 -*-
"""Datavisualisation1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15-eruBmH22tYN8NY7ZGXPLwLATLczAPs
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/titanic-training-data.csv")

df.head()

df.tail()

df.shape

df.info()

df.dtypes

df.describe()

df.isnull().sum()

sns.relplot(x="Parch",y="SibSp",data=df)

sns.relplot(x="Age",y="SibSp",hue="Embarked",data=df)

sns.catplot(x="Survived",y="Age",data=df)

sns.catplot(x="Survived",y="Age",hue="Embarked",data=df)

sns.catplot(x="Survived",y="Age",jitter=False,data=df)

sns.catplot(x="Survived",y="Age",kind="swarm",data=df)

sns.catplot(x="Survived",y="Age",kind="violin",data=df)

sns.catplot(x="Survived",y="Age",kind="box",data=df)

sns.catplot(x="Survived",y="Age",kind="bar",data=df)

sns.catplot(x="Survived",y="Age",kind="point",data=df)

sns.distplot(df.Age)

sns.distplot(df.Age, kde=False, rug = True)

sns.jointplot(x="Age",y="SibSp",data=df)